// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNGkBZQDUWxbYsCjf6-BnHpWQfDqb4Fg',
    appId: '1:312175222545:web:ec84b0326f30c867c7f6b0',
    messagingSenderId: '312175222545',
    projectId: 'ebra-app',
    authDomain: 'ebra-app.firebaseapp.com',
    storageBucket: 'ebra-app.firebasestorage.app',
    measurementId: 'G-0H3G0BJQ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIdQsAlMNm6TH5HCnWgt_T04cojx69cU',
    appId: '1:312175222545:android:03f76248b83a1ffec7f6b0',
    messagingSenderId: '312175222545',
    projectId: 'ebra-app',
    storageBucket: 'ebra-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAt5Vb75H1bKmIdTJywTjiXl_0GtogXQ',
    appId: '1:312175222545:ios:102546d9dafd6731c7f6b0',
    messagingSenderId: '312175222545',
    projectId: 'ebra-app',
    storageBucket: 'ebra-app.firebasestorage.app',
    iosBundleId: 'com.example.ataa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAt5Vb75H1bKmIdTJywTjiXl_0GtogXQ',
    appId: '1:312175222545:ios:102546d9dafd6731c7f6b0',
    messagingSenderId: '312175222545',
    projectId: 'ebra-app',
    storageBucket: 'ebra-app.firebasestorage.app',
    iosBundleId: 'com.example.ataa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpNGkBZQDUWxbYsCjf6-BnHpWQfDqb4Fg',
    appId: '1:312175222545:web:8ffa86664e4061cdc7f6b0',
    messagingSenderId: '312175222545',
    projectId: 'ebra-app',
    authDomain: 'ebra-app.firebaseapp.com',
    storageBucket: 'ebra-app.firebasestorage.app',
    measurementId: 'G-YET8WFXHMQ',
  );
}
